### ISSUE TITLE
I am having issues getting my jks file to import

### ISSUE THREAD

**Issue by jnylaan** [inductiveautomation/module-signer#3]
I keep getting the below error:

Exception in thread "main" java.security.UnrecoverableKeyException: Cannot recover key
        at java.base/sun.security.provider.KeyProtector.recover(KeyProtector.java:304)
        at java.base/sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:144)
        at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
        at com.inductiveautomation.ignitionsdk.ModuleSigner$Main.main(ModuleSigner.java:138)

**Comment by kevinherron** [comment]
Not sure what else to suggest other than make sure the KeyStore is in PFX or JKS format and that you have the correct alias and password pointing to a KeyPair in the store.

Maybe try opening it in something like KeyStore Explorer as a sanity check.

**Comment by jnylaan** [comment]
My key is valid and I have the proper password.  Do you see anything wrong with the commands below? 

**********************************************************************************

Enter keystore password:
Keystore type: jks
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: darren
Creation date: Feb 10, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Jonathan Nylaan, OU=IE, O=Wayfair, L=Boston, ST=MA, C=US
Issuer: CN=Jonathan Nylaan, OU=IE, O=Wayfair, L=Boston, ST=MA, C=US
Serial number: 7d50ed66
Valid from: Wed Feb 10 16:43:04 EST 2021 until: Tue May 11 17:43:04 EDT 2021
Certificate fingerprints:
         SHA1: 07:4E:9E:5F:0D:D5:16:C6:3D:56:B7:CE:3F:EB:00:D9:08:AB:86:28
         SHA256: B2:BF:38:AA:D4:6D:1F:EF:F6:3B:15:0B:65:CD:27:71:D0:F5:05:6C:4C:2E:C3:43:5F:62:06:BA:09:54:EF:FD
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 3E B6 95 58 5F B3 22 D4   FB D5 E9 DA 3B DC CB E0  >..X_.".....;...
0010: C0 6B BF 7D                                        .k..
]
]



*******************************************
*******************************************



Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore local.keystore -destkeystore local.keystore -deststoretype pkcs12".


When trying to run after key verification.

PS C:\Users\jn094m\DEV\module-signer> java -jar module-signer.jar -keystore=C:\local.keystore -keystore-pwd=123456 -alias=darren -module-in=C:\Users\jn094m\DEV\ignition-sdk-examples\perspective-component\build\RadComponents-unsigned.modl -module-out=C:\Users\jn094m\DEV\ignition-sdk-examples\perspective-component\build\RadComponents-signed.modl -chain=
Exception in thread "main" java.security.UnrecoverableKeyException: Cannot recover key
        at java.base/sun.security.provider.KeyProtector.recover(KeyProtector.java:304)
        at java.base/sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:144)
        at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
        at com.inductiveautomation.ignitionsdk.ModuleSigner$Main.main(ModuleSigner.java:138)

**Comment by kevinherron** [comment]
I don't see a `-alias-pwd` argument and the empty value for `-chain` might be an issue too.
